### ISSUE TITLE
Debug Error  / Couldn't start GDB Server / Blackpill STM32f411CE

### ISSUE THREAD

**Issue by SebastianWantia** [grblHAL/STM32F4xx#107]
I have a problem to start debugging with Segger J-Link and also with the ST-Link debugger.
The project compiles without a error, other projects in my workspace have no problems like this. 
I couldn't find any reason for that anyone an idea?

Error mesage is: "Error in final launch sequence: Failed to start GDB Server" 

![IMG_5235](https://user-images.githubusercontent.com/13151233/212008490-6e1ba8a2-c74f-4543-b1f5-486d174d9de0.jpg)

**Comment by dresco** [comment]
Might be worth checking whether the SWO pin is assigned to anything else in the board map? That has caught me out before..

**Comment by SebastianWantia** [comment]
The same board with a different software but same debugger works without any error. Must be something with the software.

**Comment by terjeio** [comment]
> Must be something with the software.

You are using STM32CubeIdIDE? If so is the debug configuration set up correctly? From the debug tool dropdown select "Debug configurations..." and then click the configuration you want to use to open the settings.

You may also find some hints [via a search](https://duckduckgo.com/?t=ffab&q=Error+in+final+launch+sequence%3A+Failed+to+start+GDB+Server&ia=web).

**Comment by dresco** [comment]
> Must be something with the software.

I'd still suspect the pin mapping. Is spindle sync enabled? If so, the SWO pin (PB3) is in use here..

https://github.com/grblHAL/STM32F4xx/blob/7bb854b29d2dbf11d54f6f34ab938e9cb0ec9b4a/Inc/blackpill_map.h#L124-L125

**Comment by terjeio** [comment]
> I'd still suspect the pin mapping.

This would only be possibe if an initial flashing was successful. And this statement suggest that the SWO interface is working: "The same board with a different software but same debugger works without any error."

**Comment by dresco** [comment]
> This would only be possible if an initial flashing was successful

Yeah, it may not be the problem in this instance, but mentioned as it's something I've tripped over before. Another project of mine was using the SWO pin in the code. Symptom was that flashing worked just fine, but debug would error out (understandably)..

**Comment by SebastianWantia** [comment]
Thanks for your help so far!
I haven't tried your suggestion yet. What I can say is that it worked after I created a new Project and copied all files from the GRBLHal Project in the new one. Like in the picture attached. 
Best regards
<img width="161" alt="NewProject" src="https://user-images.githubusercontent.com/13151233/212349963-44ca89dc-07f2-4938-95fd-9a182f3a4436.png">

**Comment by SebastianWantia** [comment]
> You are using STM32CubeIdIDE? If so is the debug configuration set up correctly? From the debug tool dropdown select "Debug configurations..." and then click the configuration you want to use to open the settings.

--> Yes I would say configuration, in the Debugsetting are correct see attached pictures
<img width="1226" alt="DebugSettings1" src="https://user-images.githubusercontent.com/13151233/212351854-c6657a20-5f22-4b8f-b8a7-c8e46dffbb66.png">
<img width="502" alt="DebugSettings2" src="https://user-images.githubusercontent.com/13151233/212351859-ab91f2b5-0a6f-49b7-9f01-b13b77c00721.png">
