### ISSUE TITLE
Hi great terjeio, I saw your update about Ethernet. Is Ethernet ready?

### ISSUE THREAD

**Issue by hanke-cnc** [grblHAL/STM32F4xx#122]
I am planning to manufacture and sell circuit boards with Ethernet versions for GRBLHAL. Is it ready for this? I see that the STM32F407 chip is good, mainly because it is much cheaper than the H7. It is important to keep the cost down to promote and popularize GRBLHAL. Also, since the STM32F407 chip appears to have built-in Ethernet, can I skip using the W5500 chip?

**Comment by terjeio** [comment]
It should be fairly easy to add as the code required for grblHAL itself can be copied from the F756 driver with little or no changes. The STM32 driver code has to be added as well, this should be done by creating a new F407 project in STM32 CubeIDE and adding ethernet support with the correct PHY interface. Then copy the driver code to the grblHAL project.
Additional clock setup code may have to be copied to _main.c_ as well - compare the one from the F407 project.

![image](https://github.com/grblHAL/STM32F4xx/assets/20260062/14e70e02-d903-41a3-9e87-3eb6bf018a12)
