### ISSUE TITLE
Issue when SPI_IRQ_PIN or SPI_IRQ_BIT is not used

### ISSUE THREAD

**Issue by andrewmarles** [grblHAL/STM32F4xx#128]
I think that this might want to be an ifdef:

https://github.com/grblHAL/STM32F4xx/blob/7dbf6fa1ecacac138d760679673cbb4b3d43de32/Src/driver.c#L451

When not defined, SPI_IRQ_BIT gets inndef'd to 0 and this causes a compile issue at line 470 of driver.c because spi_irq (driver_irq_hander_t) never gets intialized.

**Comment by terjeio** [comment]
Oops, it is the #ifdef at line 470 that has to be changed to #if... I'll fix that.

**Comment by terjeio** [comment]
[Fix commited](https://github.com/grblHAL/STM32F4xx/commit/6888a95a8a798f98b7c3d09766c76a3dfdde3476#diff-78adbf68c4518084f13b26f19ead59c48808a6f2a6a1823a062b91223af556f8).
