### ISSUE TITLE
Error 9 and error 79

### ISSUE THREAD

**Issue by adepacarmerah** [grblHAL/STM32F4xx#148]
hello terje, I compiled stm32 minimal blackpill via Stlink, it was successful in compiling but when using Gcode sender (openbuilds) there was an error warning 9 then disconnected, when using io sender the firmware could be detected but an error warning 79 appeared

**Comment by terjeio** [comment]
See [this Wiki page](https://github.com/grblHAL/core/wiki/First-Run-Grbl-Settings).

**Comment by adepacarmerah** [comment]
thx problems solve
