### ISSUE TITLE
Hi, preparing to conduct lathe testing experiment, should I purchase this type of encoder?

### ISSUE THREAD

**Issue by hanke-cnc** [grblHAL/STM32F4xx#154]
![a](https://github.com/grblHAL/STM32F4xx/assets/108179425/372f0297-ad0b-4f9a-a9fd-0cc2fc8cc70f)

I have looked up some information about encoders. A represents the direction signal, B represents the pulse signal, and Z indicates that one full rotation has occurred. So, should I connect B to the pulse input and Z to the index input?

**Comment by terjeio** [comment]
Yes.
