### ISSUE TITLE
option to set output pins to OD

### ISSUE THREAD

**Issue by langwadt** [grblHAL/STM32F4xx#17]
Would it not make sense to add the option to set output pins to opendrain? Many external drives with optocoupler inputs spec a minimum of 5V and since most pins on the STM32 is 5V tolerant that would be possible with the output set as OD

**Comment by terjeio** [comment]
A compile time option specified in the map file and per [pin group or per pin](https://github.com/grblHAL/core/blob/master/crossbar.h)? Or a run time configuration with new $-settings bound to the map file? 

It has to be per map file as some boards buffer outputs and changing the pins to OD for these may render them unusable.

What about the risk of frying the MCU if 5V is applied to a non-OD output pin? Are STM32 pins still 5V tolerant in push-pull (PP) mode?

**Comment by langwadt** [comment]
compile time option per group I'd say. The pins are not 5V tolerant in PP or with pullup enabled, but they will never see 5V, only 5V minus the forward voltage of the opto and a resistor 

My drivers (DM556) seems to work with 3.3V PP but it is outside spec, with 5V and PP the optos never turn off, with 5V and OD it works and is within spec

**Comment by terjeio** [comment]
Ok, then it will be like this:

```
...
#define STEP_OUTMODE            GPIO_MAP
//#define STEP_PINMODE            PINMODE_OD // Uncomment for open drain outputs
...
```
same for direction and enable signals.

**Comment by terjeio** [comment]
Change is now up.

**Comment by langwadt** [comment]
thanks, I'll try it out

**Comment by langwadt** [comment]
works as expected. I must say that a getting fork of something with changes in submodules updated seems less that intuitive

**Comment by dresco** [comment]
> I must say that a getting fork of something with changes in submodules updated seems less that intuitive

Wouldn't disagree, but fwiw you can configure your repo to automatically update submodules when pulling changes..

`git config --local submodule.recurse true`
