### ISSUE TITLE
Manually Building SuperLongBoard STM32F412

### ISSUE THREAD

**Issue by siganberg** [grblHAL/STM32F4xx#193]
Since the SuperLongBoard is not yet available in Web Builder, I'm trying to build firmware for the LongBoard32, but I can't seem to get it working, and I keep encountering errors.

So far, I have created an entry in the platformio.ini file:

```

[env:f412vg_SLB]
board = genericSTM32F412VG
custom_prog_version = SLB
board_build.ldscript = STM32F412VGTX_FLASH.ld
build_flags = ${common.build_flags} 
  -D BOARD_LONGBOARD32=1
  -D SLB_EEPROM_ENABLE=1
  -D SIENCI_LASER_PWM=1
  -D SDCARD_ENABLE=2 
  -D _VOLUMES=1  
lib_deps = ${common.lib_deps}
  FatFs
  eeprom
lib_extra_dirs = ${common.lib_extra_dirs}  
upload_protocol = stlink

```

I also added an entry in driver.json:

```
  {
      "name": "Longboard32",
      "symbol": "BOARD_LONGBOARD32",
      "URL": "https://github.com/Sienci-Labs/SuperLongBoard",
      "MAP": "boards/longboard32_map.h",
      "caps": {
        "axes": 5,
        "auto_square": 2,
        "digital_in": 3,
        "digital_out": 4,
        "eeprom": -2,
        "fram": 0,
        "i2c": 1,
        "sdcard": 1,
        "keypad": 1,
        "pio_board": "genericSTM32F412VG",
        "ldscript": "STM32F412VGTX_FLASH.ld"
      },
      "symbols": {
          "STM32F446xx": "",
          "HAS_BOOTLOADER": ""
      }
```

I copied the genericSTM32F412VG.json file to the root folder. This file can be found here: (https://github.com/Sienci-Labs/sienciHAL/blob/SLB_Bringup_Dev/genericSTM32F412VG.json).

Then, I executed the following command:

```
pio run -e f412vg_SLB
```

I started with fewer plugins to have a successful build, but I keep getting errors after fixing one issue. Before going down the rabbit hole of trying to fix all the errors, I figured I'd ask if anyone has already had a successful build.

The reason I am building this is that the core of the Sienci grblHAL firmware is not up to date.

**Comment by terjeio** [comment]
Here is the platformio.ini I use to build the latest version with VSCode/PlatformIO:
Note that this build has not been verified yet!

[platformio.zip](https://github.com/user-attachments/files/17372498/platformio.zip)

**Comment by siganberg** [comment]
Do you have the extra scripts?


```
extra_scripts = 
    pre:extra_script.py
    post:extra_script.py
```

![image](https://github.com/user-attachments/assets/f5d83376-5652-4dd0-980b-5f23eba392d1)

**Comment by siganberg** [comment]
Not sure if the script is important but if I take it out, I'm getting this errors:

![image](https://github.com/user-attachments/assets/3735709b-3132-4e97-b0c6-05e678946a40)

**Comment by terjeio** [comment]
> Do you have the extra scripts?

It is found [here](https://github.com/Sienci-Labs/sienciHAL/blob/SLB_Bringup_Dev/extra_script.py).

> Not sure if the script is important but if I take it out, I'm getting this errors:

Do you have the latest grblHAL version?

**Comment by siganberg** [comment]
The core?  Yes

![image](https://github.com/user-attachments/assets/047ea566-9934-40ad-890c-70e5834e7351)

I manage to have successful compilation by disabling the the following. Will adding there custom plugins and looking to fix those 2 flags. 

```
 -D EVENTOUT_ENABLE=0
  -D STATUS_LIGHT_ENABLE=0
 ``` 

Thanks a lot for the help, really appreciate it.

**Comment by terjeio** [comment]
> Will adding Sienci custom plugins and looking to fix those 2 flags.

Do a recursive pull to get the latest submodules instead, recently a new one was added for the two you disabled.

**Comment by siganberg** [comment]
> Do a recursive pull to get the latest submodules instead, recently a new one was added for the two you disabled.

I already did a recursive pull but I'm still getting errors with those two flags turned ON. For now, I've kept them OFF. I'm also just adding the custom Sienci plugins they included, such as `boot_entry`, `rgb`, and `probing`. Anything that matches with the repo, I left as is and pulled the latest changes.

I loaded the firmware for the SLB. The issue is that the motors are not getting power after I performed a firmware reset. Restoring the SienciHal firmware brings the stepper motors back online. Before resetting, the motors had a slightly high-pitched sound when moving. I'm not sure if this is caused by the settings for the TMC2660. Setting number don't much, they are off by 1. 

![image](https://github.com/user-attachments/assets/690b9821-a169-4549-8758-7df0257107cd)

**Comment by terjeio** [comment]
Boot entry is part of the base driver so not needed, basic RGB support is also, with a core defined API. I have not looked into the probing plugin yet. There should be a _plugins_ folder with the eventout and rgb plugins:

![image](https://github.com/user-attachments/assets/5197cf0f-2095-4904-92c6-74e5b66902f3)

If not [download and add it manually](https://github.com/grblHAL/Plugins_misc) - making it generally available is still work in progress.

> I loaded the firmware for the SLB. The issue is that the motors are not getting power after I performed a firmware reset. 

What is your $4 setting? And M122 output?

> Setting number don't much, they are off by 1 whey I compare with SienciHal.

Some SienciHal setting numbers were added without requesting them from me and they were already assigned for other purposes. So those had to change. Reloading SienciHal settings into grblHAL is thus a bad idea.

**Comment by siganberg** [comment]
Pulling the `Plugins` fixed the two issue with enabling `EVENTOUT_ENABLE` and `RGB_LED_ENABLE`. It's not currently added on this repo. 

There is another flag `STATUS_LIGHT_ENABLE` which is on the `rgb` plugins of sienci so  If take it off I also need to turn that off.  Already remove the `boot_entry` as you suggested. 

> Some SienciHal setting numbers were added without requesting them from me and they were already assigned for other purposes. So those had to change. Reloading SienciHal settings into grblHAL is thus a bad idea.

I agree, that's why I'm trying to switch. :D

**Comment by siganberg** [comment]
Here's my test result.

- Homing doesn't work and freeze the board, need hard power cycle. 
- Jogging doesn't update the coordinates. 
- Hitting e-stop doesn't show any ALARM.  Reconnecting the board then shows the ALARM 10. Resetting e-stop doesn't work or unlocking the machine ($X). Require hard reboot to continue.
- typing in the  console doesn't show any response like getting value of ${parameter} or $$.

What works so far:

- Jog dial works. 
- Spindle (modbus) 

I'm using gSender since I don't have any other grblHal sender to try on macos. 

Attaching diagnostic file from gSender which has all the firmware paramenters. 

[diagnostics_10-15-2024_09-53-05.pdf](https://github.com/user-attachments/files/17382144/diagnostics_10-15-2024_09-53-05.pdf)

**Comment by terjeio** [comment]
> Homing doesn't work and freeze the board, need hard power cycle.

This has now been fixed. 

The rest I am not so sure about, can you connect with a terminal and try some commands from that?
FYI I do not have a SLB with me where I am now so cannot test myself, other drivers I do have access to works as they should so you may have wait a bit for the rest to be resolved.

**Comment by siganberg** [comment]
Great! I will test it tomorrow.  

IMHO, Sienci should send you one for the great work you been doing.  👍

**Comment by terjeio** [comment]
> IMHO, Sienci should send you one for the great work you been doing.

I have one at home, but I am away for 3 more weeks...

**Comment by siganberg** [comment]
Try the latest. I initially still got problem with the homing so decided to do RST and start from scratch. So far everything is working except for the tool set routine with my RapidChangeATC. 

When I touches the tool setter, it stop and freeze the board. 
https://youtu.be/h3W3Max4_Ig?si=RnjEP9GS6LAyygQp&t=58

Things that doesn't work before properly with SienciHal is when I execute M6T98 (unloading), I'm getting error and doesn't completely set the tools to 0. 
Reference: https://github.com/greilick-industries/rcatc-scripts-grblhal
Tool Change Macro: https://github.com/greilick-industries/rcatc-scripts-grblhal/blob/main/macros/TC.macro

**Comment by terjeio** [comment]
FYI I have commited some fixes to expression handling that may help if it is a hang, not a crash.

**Comment by siganberg** [comment]
I found some time to test the latest and build it successfully, but I can't get it to work. I can connect to the device, but I'm not getting any response from the board. 

<img width="527" alt="image" src="https://github.com/user-attachments/assets/fb5a2160-bcd3-476c-b707-071c638b4e23">

**Comment by terjeio** [comment]
Odd, it is working for me. Perhaps I should make a binary available for you to try?

The SLB will be made available in the Web Builder when Chris gives the green light for adding it, hopefully soon.

**Comment by siganberg** [comment]
So this STM32F4xx repository works out of the box for you without any changes (except maybe the platform.io configuration and the Python script)?

Yeah, send me your binary so I can try it. My current SLB also has an EEPROM issue; it won’t even work with the stock SienciHAL firmware unless I compile their version with EEPROM disabled and just use the SD card. I’ll test your binary on the replacement board once it arrives.

Meanwhile, could you also send me your latest platformio.ini that works? I’d like to compare it with mine and see what’s different.

Many thanks!

**Comment by terjeio** [comment]
> So this STM32F4xx repository works out of the box for you without any changes (except maybe the platform.io configuration and the Python script)?

Yes, except the Python script has not been changed. I develop with STM32CubeIDE so the build options are not the same as with PlatformIO, however the provided build is made with PlatformIO and with EEPROM disabled. Also be aware that I only bench test with one motor connected so is to be considered as alpha quality for now.

Note that some setting numbers are different, either erase the flash before programming or reset settings to default with `$RST=*`.

The binary/.ini can be downloaded from [here](https://www.io-engineering.com/downloads/slb_bin.zip), I'll keep the link active for a short while.

**Comment by siganberg** [comment]
Thanks I'll try and report back. 👍

**Comment by siganberg** [comment]
I tested both the binary and the latest compiled code using the provided platform.ini file with consistent result:

Here are the results of my testing:

- I can connect to the machine, but I am only able to execute jog commands.
- Executing the home command causes the board to hang, requiring a power cycle to recover.
- In gSender, sending ${xx} in the MDI produces no response. The same issue occurs in ioSender unless the "Verbose" checkbox is enabled.

**Comment by terjeio** [comment]
The fix has now been commited.

**Comment by siganberg** [comment]
Here's the new result of the new build. 

- Connecting to the board I'll get printout in the terminal of all the settings which populate also the User Interface firmware settings of the gSender, but can only modify one value at time, then I need to disconnect and connect again. Typing any command in the terminal doesn't give me any effect or any response, like `$$` command or `M61Qn` when I'm trying to set the my current tool or actually any command. 
- Homing start moving but start crash on the limit even though the homing sensor are triggering. Need to hit the e-stop to avoid damanging the motor.

**Comment by terjeio** [comment]
> My guess is that gSender is confused by the $spindles command output and acts weirdly after.

I have now confirmed that this is the reason...

**Comment by siganberg** [comment]
> If you trigger the limit switches manually does the Signals LEDs in ioSender change state? I have a pending commit where they do.

I might need to reflash the firmware and retry again with ioSender.  I put back the sienceHal as need to run some project right now. Although the sienceHal is usesable, it's annoying getting random invalid g-code error. 

> I have now confirmed that this is the reason...

Is this something fixable? So this is the reason of MDI interaction eractic on gSender? Or this something that need fixing on the gSender side?

**Comment by siganberg** [comment]
> New [patched binary](https://www.io-engineering.com/downloads/slb_bin3.zip) uploaded. It has Siencis customized version of the `$spindles` output. There may be other issues present as well since jog distances changes to `NaN` on connect or when sending `$I` from the console. Note that I will not add their customization so the binary is just for testing.

Is it possible to get the hex version so I don't need to reinstall the STM programmer and I can do it on the gSender?

Or better yet, just push a separate branch that I can pull and compile myself. And from here we can just continue working on this branch, whatever fix we do or testing.

**Comment by terjeio** [comment]
> Is this something fixable?

Yes.

> So this is the reason of MDI interaction eractic on gSender?

Yes it seems so, at least gSender behaves better when I add the customization.

> Or this something that need fixing on the gSender side?

Yes, IMO it is better if gSender works with "standard" grblHAL controllers. There is even a comment in the gSender code that they should switch to the machine readable output from `$spindlesh`...

**Comment by terjeio** [comment]
> Is it possible to get the hex version so I don't need to reinstall the STM programmer and I can do it on the gSender? gSender only accept .hex.

Now available in the download.

> Or better yet, just push a separate branch that I can pull and compile myself. And from here we can just continue working on this branch, whatever fix we do or testing.

I have a settings revision nearly ready to commit so creating a branch that includes all the changed drivers and submodules will be far too much work. However, the customization is just [these lines,](https://github.com/Sienci-Labs/grblhal_core/blob/c6d50137f7b8aaf5b7e80992f3e6cd1f25e32959/report.c#L2219-L2238) so you may add them manually if you wish.

**Comment by siganberg** [comment]
Awesome! I will test it and report back.

**Comment by siganberg** [comment]
All the issue mentioned before are fix but here are the issue

Shows stopper issue:

- Probing doesn’t work and hangs the board after it touches the probe/tool setter
https://youtu.be/KWiwDztz-8g?si=coCrCNNnD5NXUhf1a

Annoyances issues:

- Hitting e-stop and release it doesn’t recover, need hard power cycle.
- Still keep getting this error randomly. If issue jog, then do it again for the same command, the error is not appearing anymore. This is actually the problem with sienceHal too that I’m trying to if it’s resolve.

￼
<img width="399" alt="client G53 G90 GO X10" src="https://github.com/user-attachments/assets/5d029f45-7aa7-426e-b9f6-9ce1a149d444">

**Comment by terjeio** [comment]
Probe hang is on me, due to the many inputs in the SLB. Fixed in [this hex](https://www.io-engineering.com/downloads/slb_hex4.zip).

E-stop works for me, both in ioSender and gSender (1.4.10). gSender is a bit slow on responding to unlocking sometimes.

The random error is likely a gSender bug? Related to jog distances getting reset to NaN? No such issue with ioSender.
BTW I get the same random errors connected to a MSP432 controller.

**Comment by siganberg** [comment]
The probe is working now, so my tool setter is too, since they are just series together. I need to reboot first before it starts working. 

The e-stop unlocking works, but it doesn't return the stepper motor's power back and needs a power cycle. Just scroll on the 4:12 timeline for this issue: https://youtu.be/fsx9jLBmbsY?si=qr9HB4-m_kwMJsn2&t=253

**Comment by terjeio** [comment]
> The e-stop unlocking works, but it doesn't return the stepper motor's power back and needs a power cycle.

Oops, I missed that one. Power is cut to the motors on e-stop so the stepper drivers loose their configuration.
[This hex](https://www.io-engineering.com/downloads/slb_hex5.zip) reinits them after the e-stop is cleared.

**Comment by siganberg** [comment]
Thanks. Will test it tomorrow.

Can I get code changes for it? I'm keeping my fork updated with these fixes.

**Comment by terjeio** [comment]
Code changes just committed.
You'll have to change `-D DEFAULT_SPINDLE=0` to `-D DEFAULT_SPINDLE=11` in _platformio.ini_ to get the correct spindle.

**Comment by siganberg** [comment]
Good new. Everything works now. 

With the new version, it fixes my problem too when doing just unloading tool and also tool measurement. Before these give me bunch of errors. 

There is a minor issue I keep getting, this might be on the gSender side. If I  issue a invalid command let say M61T1 (it supposed to be M61Q1) for telling the firmware what current tool is loaded, it give's me invalid g-code error which should be right but any succedding valid g-code command will still throw invalid g-code until I do some jogging.

**Comment by terjeio** [comment]
> ...  any succedding valid g-code command will still throw invalid g-code until I do some jogging.

This is a safety feature in grblHAL, when an error is returned it will be returned for all subsequent g-code commands until a blank line or a $ system command is sent. Legacy Grbl will just continue executing commands.
Sadly gSender does not allow sending blank lines, neither do so automatically after an error when a new command is sent from the MDI. IMO gSender should at least allow sending blank lines - they do no harm.

**Comment by siganberg** [comment]
Ahh make sense. Will check on the gSender side.

**Comment by siganberg** [comment]
Do you have the hex that enable the EEPROM. I do have the new SLB replacement. I can recompile it but not sure where to add this [changes](https://github.com/Sienci-Labs/grblhal_core/blob/c6d50137f7b8aaf5b7e80992f3e6cd1f25e32959/report.c#L2219-L2238) with the latest core.

**Comment by terjeio** [comment]
You can now build using the [Web Builder](http://svn.io-engineering.com:8080/?driver=STM32F4xx&board=SuperLongBoard%20%28SLB%29), it will output a hex for the SLB.

> I can recompile it but not sure where to add this [changes](https://github.com/Sienci-Labs/grblhal_core/blob/c6d50137f7b8aaf5b7e80992f3e6cd1f25e32959/report.c#L2219-L2238) with the latest core.

Before [this line](https://github.com/grblHAL/core/blob/c608a1cd29b79311b001fa200c5b1a53e31a546e/report.c#L2560).

**Comment by siganberg** [comment]
Oh SLB is now available on web builder. I’ll check it out.

**Comment by siganberg** [comment]
Building code is working good now. Didn't use the Web Builder as there are some many parameters that I haven't time to configure and test.

I'm closing this ticket is it's getting too long. I will just create a separate ticket to track some findings .

Thanks again for fixing some of the issues.
