### ISSUE TITLE
TMC2209 current setting

### ISSUE THREAD

**Issue by paukstelis** [grblHAL/STM32F4xx#197]
I've been working on including an alternate STM32F407 board (Mellow Fly CDY V3). Basing if off the SKR 2.0 and everything seems to work, but I see some odd behavior when I am playing around with setting TMC2209 driver current. With my LPC17x builds, I can set the 2209 current up to 2000 mA. For the STM build I can set the motor current up to 979 mA before getting an out-of-range error. It is unclear to me where/how this limit is being set. Any insights?
Thanks.

--p

**Comment by terjeio** [comment]
> It is unclear to me where/how this limit is being set. Any insights?

It is a calculated value, and wrongly so. Fix [committed](https://github.com/terjeio/Trinamic-library/commit/d64f2a1ab56d24c36675ab5c4cbd4b10e400b6df).
