### ISSUE TITLE
sound when move motors using tmc2209 after update 

### ISSUE THREAD

**Issue by semos2k** [grblHAL/STM32F4xx#199]
I have updated the version of GRBLHal that I was using since January 15 and when updating to the current version my motors have started to make a noise, I am using the same amperage configuration for the motors, the same step and speed configuration, the driver is tmc2209 and nema 17 motors (0.9a and 1.4a).

Should I do something additional to remove this noise?

**Comment by terjeio** [comment]
When rechecking the code I found one parameter that was changed when I refactored some parts of the code earlier. I have restored that in the latest commit.

I have also an option for adding a number of low-level settings that can be used to tune the motors, now available in the Web Builder. If compiling yourself you can enable this by adding `#define TRINAMIC_EXTENDED_SETTINGS 1` in _my_machine.h_.
Note that adding (or removing) this option will reset all plugin setting values to default.

![image](https://github.com/user-attachments/assets/cf7bbc57-09a2-4236-8a92-35268050d6a2)

**Comment by semos2k** [comment]
Thx, works perfectly.
