### ISSUE TITLE
Y limit switch not being read correctly

### ISSUE THREAD

**Issue by dresco** [grblHAL/STM32F4xx#2]
Just a typo in the bitband specific code for the Y axis (max not min)..

https://github.com/grblHAL/STM32F4xx/blob/906d7b12a72548fd64c8faa2a7659967c29c9413/Src/driver.c#L490-L493

**Comment by terjeio** [comment]
Thanks, I'll fix that too. The signals min value should also be initalized to the invert mask as the a input may not be available.

**Comment by terjeio** [comment]
Fixed.
