### ISSUE TITLE
Automatic square, limit switch always active

### ISSUE THREAD

**Issue by semos2k** [grblHAL/STM32F4xx#200]
Hi, I am trying to activate the auto square feature, my board is a skr pro v1.2 and it has a limit switch available for each motor, when checking with ioSender it always shows the limit switch active and when activating them by hand they do not change state.

I have seen some videos on youtube and a blog but I have not found a solution. Should I only activate one limit switch for this feature or can I continue using the two that the card has available?

**Comment by semos2k** [comment]
The switch works when use only one.

**Comment by semos2k** [comment]
![image](https://github.com/user-attachments/assets/5a2990e7-c16d-42d2-86b6-e05833cb5c49)
this is diagram for the wiring.

**Comment by terjeio** [comment]
Is the corresponding LED changing state when you activate a switch?

**Comment by semos2k** [comment]
Hi Terjeio, you were absolutely right. I'm using a TMC driver and one of them was active with the sensorless home pins. Thank you very much for your time.
