### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by higgie0807** [grblHAL/STM32F4xx#47]
Trying to build "pio run --environment nucleo_f446re_protoneer" but the STM32F4xx/grbl dir is empty- 

In file included from USB_DEVICE/App/usbd_cdc_if.c:26:0:
Inc/driver.h:41:10: fatal error: grbl/driver_opts.h: No such file or directory
 #include "grbl/driver_opts.h" 

so missing at least grbl/dirver_opts.h, and probably more

**Comment by terjeio** [comment]
You have to [pull the submodules](https://github.com/grblHAL/core/wiki/Compiling-GrblHAL) to get the contents.

**Comment by higgie0807** [comment]
Ah, thanks for the hint.  Seems a little non-intuitive, but...
