### ISSUE TITLE
errors compiling STM32F4xx

### ISSUE THREAD

**Issue by acaballero6270** [grblHAL/STM32F4xx#49]
Attempting to compile STM32F4xx for Bigtreeteck SKR2 I get the following errors:
Using platformio:
.pio/build/btt_skr_2_tmc5160/src/driver.o: In function `driver_init':
driver.c:(.text.driver_init+0xb6): undefined reference to `i2c_init'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\btt_skr_2_tmc5160\firmware.elf] Error 1
=================================================== [FAILED] Took 9.67 seconds ===================================================

Environment        Status    Duration
-----------------  --------  ------------
btt_skr_2_tmc5160  FAILED    00:00:09.673

Using STM32CubeIDE:
c:\st\stm32cubeide_1.8.0\stm32cubeide\plugins\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.9-2020-q2-update.win32_2.0.0.202105311346\tools\arm-none-eabi\bin\ld.exe: ./Src/driver.o: in function `driver_init':
driver.c:(.text.driver_init+0xb6): undefined reference to `i2c_init'
collect2.exe: error: ld returned 1 exit status
make: *** [makefile:79: grblHAL F407 8MHz.elf] Error 1
"make -j16 all" terminated with exit code 2. Build might be incomplete.

11:16:46 Build Failed. 3 errors, 0 warnings. (took 607ms)

I followed the instructions in here to the letter. AM I doing something wrong?

**Comment by terjeio** [comment]
> AM I doing something wrong?

No, comment out or remove this line for now :

https://github.com/grblHAL/STM32F4xx/blob/4e9600e9159927723e6f7af58c1cb3fc43d035fc/Inc/btt_skr_2.0_map.h#L37

**Comment by acaballero6270** [comment]
That seemed to work!!
Thank you very much. Specially for your super fast response!!
