### ISSUE TITLE
MPG + Modbus

### ISSUE THREAD

**Issue by JoachimF** [grblHAL/STM32F4xx#55]
Hello Terjeio,

Congratulation for your work, I'm a big fan!

Have you planned to use the 3 uarts on the F401, because on my modular router I have a
 - hyuang VFD, UART
 - or Plasma THC adc (i2c adc?)
 -  XYYZA(B if possible) XYZ for router, AB or AY to keep 2 io ports for hotwire foamcutter module
 - hotwire (pwm, dual spindle mode)
 - probe, 
 - I plan to use a DRO/MPG UART
 
Also I have a lathe, WM210, that I plan to CNCize, I need to understand how to wire the encoder to the blackpill.
I plan to make a breakout for the blackpill with optos and external stepper drivers if I can validate all this peripheral, 
The goal is to have the same breakboard for the router and the lathe (one for each) and share the DRO/MPG

Do you think all this stuff could fit in a STM32F401?

If I can validate all this peripheral, I plan to make a breakout for the blackpill with optos and external stepper drivers.

I have work to do, the router is working on GRLB 328p and fully operationnal as router XYZ, I need to migrate to GRBLHal on the good CPU, for the plasma, I need to get the arcok and the arc-voltage to test the THC and the most important I need a water receptacle under the metal to cut, the foamcutter module is in project for now .

I need a little help for mapping all this pins (encoder, thc..), and I can test code when all will be wired.

Thank you for all your work

**Comment by terjeio** [comment]
> Have you planned to use the 3 uarts on the F401

Not in the basic configuration. However, further ports can be added in board specific code - at least one user has done that successfully, he added two ports. You can copy the existing serial port code and modify that so it is not too hard.

> Do you think all this stuff could fit in a STM32F401?

That depends on the version of the chip? You have to consult the datasheet(s) to find out.
