### ISSUE TITLE
Connecting to iosender.exe does not work: Windows error 87; wrong parameter

### ISSUE THREAD

**Issue by tarenergy** [grblHAL/STM32F4xx#6]
There is a single line difference in STM32F4xx\Middlewares\ST\STM32_USB_Device_Library\Class\CDC\Src\usbd_cdc.c between the "old" repository and the "new" on.

Line 470 from the "old" repository:
 memset(pdev->pClassData,0,sizeof(USBD_CDC_HandleTypeDef)); // THIS LINE WAS ADDED
is missing in the "new" repository
After pasting this line the problem disappears

**Comment by terjeio** [comment]
Spooky - added by whom? I updated to the latest drivers from ST and the line is gone...

BTW I have not seen this eerror on my end, so thanks for finding the reason and reporting.
