### ISSUE TITLE
Starting factory bootloader via Grbl command

### ISSUE THREAD

**Issue by GatzeTech** [grblHAL/STM32F4xx#62]
First of all thank you for this wonderfull repo and I don't know if this is the right place for the question I have. It's not an issue but more about adding a feature.

I'm almost finished converting a Mach3 board to Grbl, first I used the Mega 5x repo, but later on I saw this active repo and also that the possibilities for adjusting the spindle pwm is a bit bigger. Inverting with the Mega 5x software was doable, but here it is one define and also frequency is easier adjustable (I have slow optocouplers on my board, so the frequency can't be to high)

Because the drivers where integrated on the PCB it was quite some work, had to solder small wires from a Blackpill to the PCB.

Anyway, I was wondering if it would be possible to start the factory bootloader via a Grbl command ? I'm using a STM32F401 (blackpill). Then for updating/changing firmware with STM32CubeProgrammer I don't have to open the housing and press the boot and reset buttons. I have some experience with programming (couple of years fulltime embedded programmer for AVR chips), but where to start ? Where are the Grbl commands processed ? I have already some example code to start the bootloader (not tested yet, because I've only one Blackpill), but where to put ? It's now a bit overwhelming ;)

![DSC_0645](https://user-images.githubusercontent.com/81743391/154633932-63b85bff-7b35-4414-8a41-45b220ac3669.JPG)

**Comment by terjeio** [comment]
You can add a $-command in a [plugin](https://github.com/grblHAL/plugins) like [I have done here](https://github.com/grblHAL/Templates/blob/928fa2e2d9e8625300a3ecbc60af7ae306f667be/my_plugin/hpgl/motori.c#L624-L652).
