### ISSUE TITLE
F411 Blackpill Homing

### ISSUE THREAD

**Issue by vvv1954** [grblHAL/STM32F4xx#65]
I have limit switches for 3 axes and they are working well as hard limits. But when I am trying to make homing it just starts with Z-axis, moves for a little (DRO shows DEFAULT_HOMING_PULLOFF value) and stops with ALARM:8 and error:9. 
I tryed homing with NO and NC switches (changing the wiring and settings) - the same results. When I am pressing a switch during the movement, the state of corresponding pin is changed but the controller does not feel this action.

**Comment by vvv1954** [comment]
A couple of pictures
Initial state
![image](https://user-images.githubusercontent.com/77076378/160733015-1285d53f-38b3-49b6-aff0-07ab4f99006c.png)
After homing
![image](https://user-images.githubusercontent.com/77076378/160733107-c939f4fc-c626-4d50-b3f8-44c71bada90f.png)

**Comment by terjeio** [comment]
I have checked with a F411 Blackpill and that works as well.
If you set $45 to 0 and $44 to 1 to enable homing for X-axis only does that work?

**Comment by vvv1954** [comment]
No, it is not working.
What kind of F411 Blackpill do you have, is it original from WeAct? I have this clon of WeAct from Ali
https://www.aliexpress.com/item/1005001621784672.html?spm=a2g0o.order_list.0.0.21ef18024mG9wb

**Comment by vvv1954** [comment]
I have this wiring that works with STM32F407ZGT6.  
![image](https://user-images.githubusercontent.com/77076378/160926629-5547fc58-d8c3-4245-a4ad-079f27f0e1c0.png)

**Comment by terjeio** [comment]
> What kind of F411 Blackpill do you have, is it original from WeAct? 

I believe it is a clone as it is unbranded. The link I used to buy it from is dead.

> I have this wiring that works with STM32F407ZGT6.

I would move the 3K3 resistor to the collector side. Or at least disable the MCU pullup resistors with $18 as the 3K3 resistor and the pullup will form a voltage divider when the transistor is off...

Since the codebase is shared by the F407 and the F411 I believe your issue is either electrical or related to the configuration.

**Comment by vvv1954** [comment]
I have changed the wiring as you recommended but it also does not work.  Now I want to check where is the problem: my setup or some defect of MSU. Could you attach please your firmware, wiring and $$ settings for F411 Blackpill?

**Comment by terjeio** [comment]
[GRBL Driver STM32F401.zip](https://github.com/grblHAL/STM32F4xx/files/8394956/GRBL.Driver.STM32F401.zip)

Wiring is direct to my CNC machine simulator. Note that the binary is a test build that has a lot of changes to spindle handling so may no be used for production.

**Comment by vvv1954** [comment]
Many thanks.
As far as I understood from settings, your wiring is something like this?
![image](https://user-images.githubusercontent.com/77076378/161298717-3cf16223-aa24-430e-8536-7c35aaa26223.png)

**Comment by vvv1954** [comment]
I checked homing with your firmware. It works perfectly well with both wiring above.
![image](https://user-images.githubusercontent.com/77076378/161325990-c195c0a4-8861-4616-aea7-434514766454.png)

And I understood what was wrong. I re-assigned limits pins to B3, B4, and B5. But for some reasons the homing did not want to work with these pins. So I returned limit pins to their original assignments (B12, B13, B14) and now there is no problem with homing.

Thank you very much for your help and for excellent codes!

**Comment by terjeio** [comment]
You have to change the LIMIT_INMODE to GPIO_SHIFT3 to use B3-5:

```
// Define homing/hard limit switch input pins.
#define LIMIT_PORT              GPIOB
#define X_LIMIT_PIN             3
#define Y_LIMIT_PIN             4
#define Z_LIMIT_PIN             5
#define LIMIT_INMODE            GPIO_SHIFT3
```

When I did that homing works for those pins as well.

**Comment by vvv1954** [comment]
My fault, I did not pay attention to shift. Thank you, now it works.

**Comment by vvv1954** [comment]
Last question (I hope). How to show work and machine coordinates during homing?

**Comment by terjeio** [comment]
> How to show work and machine coordinates during homing?

Not possible without [changes to the core and drivers](https://github.com/grblHAL/core/blob/dae7d56ab5ed6fcaa787aa181ef1ae331a03c9b1/limits.c#L228-L233). Limit switches are polled during homing, and only the abort realtime command is responded to to keep switch response time low.

**Comment by vvv1954** [comment]
I made a PCB for my CNC 3018, works perfectly well, thank you for excellent codes.
![STM32F PCB](https://user-images.githubusercontent.com/77076378/162581950-8268d186-24df-4752-b185-55812949caed.jpg)

**Comment by BasisSun** [comment]
> You have to change the LIMIT_INMODE to GPIO_SHIFT3 to use B3-5:
> 
> ```
> // Define homing/hard limit switch input pins.
> #define LIMIT_PORT              GPIOB
> #define X_LIMIT_PIN             3
> #define Y_LIMIT_PIN             4
> #define Z_LIMIT_PIN             5
> #define LIMIT_INMODE            GPIO_SHIFT3
> ```
> 
> When I did that homing works for those pins as well.

What exactly does GPIO_SHIFT3 stand for?

**Comment by terjeio** [comment]
> What exactly does GPIO_SHIFT3 stand for?

Shift the contents read from the GPIO input register right 3 bits before storing the result. Requires the bits in the GPIO register to be consecutive and in the axis order. [Other options](https://github.com/grblHAL/STM32F4xx/blob/7d0132aeecd24ab9ae9633db3cd79fbe99bd3576/Inc/driver.h#L97-L112).
