### ISSUE TITLE
GPIOE not working on STM32F4

### ISSUE THREAD

**Issue by tarenergy** [grblHAL/STM32F4xx#7]
The Makerbase MKS Robin Nano V3 board (STM32F407VGT6 based) has step/dir/en signals on GPIOE but the GPIOE clock is not turned on by default. 

In main.c:

static void MX_GPIO_Init(void)
{
  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOH_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOD_CLK_ENABLE();
}

Adding   
__HAL_RCC_GPIOE_CLK_ENABLE(); 
fixes that.

**Comment by terjeio** [comment]
Fixed in the latest commit. Did you make a new board map file for this board? If so can you share it, either by making a PR or upload it here?
