### ISSUE TITLE
Spindle direction pin in driver.c

### ISSUE THREAD

**Issue by JoachimF** [grblHAL/STM32F4xx#72]
Hi Terjeio,

I think the #ifdef SPINDLE_DIRECTION_PIN is missing in the  spindleSetState () function [https://github.com/grblHAL/STM32F4xx/blob/bd2ce508699ccf0a55fd7490976e53b63792897d/Src/driver.c#L1050](url)

`static void spindleSetState (spindle_state_t state, float rpm)
{
    if (!state.on)
        spindle_off();
    else {
#ifdef SPINDLE_DIRECTION_PIN
        spindle_dir(state.ccw);
#endif
        spindle_on();
    }
}

Regards,

**Comment by terjeio** [comment]
You are correct, will fix in the next commit.

**Comment by terjeio** [comment]
Fixed.
