### ISSUE TITLE
Compiling for blackpill_f411ce

### ISSUE THREAD

**Issue by wibsea** [grblHAL/STM32F4xx#82]
I am trying to compile STM32F4xx, my steps are:
git clone --recurse-submodules https://github.com/grblHAL/STM32F4xx
pio run --environment blackpill_f411ce
And I get an error:
Src/driver.c: In function 'systemGetState':
Src/driver.c:998:49: error: request for member 'reset' in something not a structure or union
      signals.reset = settings.control_invert.mask.reset;
Please advise how to solve this problem

**Comment by terjeio** [comment]
Try changing line 998 to  `signals.reset = settings.control_invert.reset;`

**Comment by wibsea** [comment]
Thank you!!  Everything compiled!
