### ISSUE TITLE
Z hard limit not triggered with BOARD_PROTONEER_3XX and Nucleo F446RE

### ISSUE THREAD

**Issue by jielemon** [grblHAL/STM32F4xx#99]
Homing runs well in X, Y, Z axes indicating that the hard limit switches (NC) in all three axes work normally. 

After that I sent "g0 g91 X10", "g0 g91 Y10", "g0 g91 Z10" to intentionally trigger the hard limit switches. But the hard limit switch in the Z axis can't be triggered while both the X and Y hard limit switches were triggered.

**Comment by terjeio** [comment]
Bugs - to be fixed in the next commit. Z-limit has to be polled since it has the same pin number as X preventing enabling interrupt handling for it.
